### ISSUE TITLE
Heyya! You! :D

### ISSUE THREAD

**Issue by ComputerErika** [ImperatorStorm/ImperatorStorm#1]
I have a question for you about the source of your pfp but this is is the only way I found to message you xD
Did you make the outline of that? Or do you know who did? Im trying to credit whoever they are but the friend who showed me the outline doesn't know, so Im on a quest now and I reverse imaged searched the outline and only found you, so here I am!

**Comment by ImperatorStorm** [comment]
PFP was a gift from a friend.

**Comment by ImperatorStorm** [comment]
Had to go digging a bit
`A Tuna Can#5862` on discord

**Comment by ComputerErika** [comment]
Thanks for the lead in the case :D
I shall take my leave
